### ISSUE TITLE
Node path string does not work

### ISSUE THREAD

**Issue by BastiaanOlij** [GodotNativeTools/godot-cpp#103]
Doing the following:

```
NodePath path(mystring)
String path_string = path;
```

Does not seem to work. path_string will be empty. When looking into path it is properly set.
The problem is that this also means copying the NodePath variable to another NodePath does not work because internally that re-passes the string.

Note sure yet why.

**Comment by SirRamEsq** [comment]
If you're just trying to convert a NodePath to a string, you can do
`var string_val = str(node_path_value)`

**Comment by BastiaanOlij** [comment]
Closing this, can't remember what we did but I'm pretty sure we fixed this ages ago :)
