### ISSUE TITLE
Using C++11 variadic templates to streamline registering and emitting signals that take arguments?

### ISSUE THREAD

**Issue by danielytics** [GodotNativeTools/godot-cpp#106]
In my GDNative experimentation today, I found that registering signals with arguments requires that a `Dictionary` whose keys are the argument names and values are the argument types must be constructed and passed into `register_signal`, and when emitting a signal with arguments, an `Array` of the argument values must be constructed and passed to `emit_signal`.

I wrote this little helper to streamline this in my code: https://gist.github.com/danielytics/41b054b260432b2e641c37c501154b47

This allows me to simply do

```c++
// Am I using the correct type enum/constant? This seems to work.
register_signal<Foo>("my_signal", "argument1", GODOT_VARIANT_TYPE_STRING);
register_signal<Foo>("test", "arg_one", GODOT_VARIANT_TYPE_STRING, "arg_two", GODOT_VARIANT_TYPE_INT);


// Passing owner in because I didn't want to change any of the binding classes, but could just as easily have made owner->emit_signal(...) work
emit_signal(owner, "my_signal", "value_for_argument1"); 
emit_signal(owner, "test", "hello", 5);
```
 This seems to work pretty well in my test code so far.

My question is if there is any interest in integrating something like this into `godot-cpp` itself? If so, I'll happily make a go at it and open a PR.

**Comment by karroffel** [comment]
That would actually be very useful! The signal registering change is very nice, maybe a small arg type could be implemented that implements an initialization list as constructor, so the name and type can be properly associated?

Currently variadic functions accept an Array, but if there's a way to get rid of that and use templates for those then I'm all for that!

**Comment by danielytics** [comment]
Great! I’ll get a draft PR ready and we can decide where to go from that.

**Comment by danielytics** [comment]
I have started work in my fork. I have a few style questions. Well, one so far, which I've added as an inline comment in my first commit: https://github.com/danielytics/godot-cpp/commit/63f9b0b9fd27c0b93c454c108e92ebc1759d3382#r27948515

re: `maybe a small arg type that implements an initialization list `, I'm not sure how to do that. `std::initializer_list` only supports a single templated type. Or do you simply mean `Arg("name", GODOT_VARIANT_TYPE_STRING)`?

**Comment by danielytics** [comment]
My second commit[1] adds an `emit_signal` template function to GodotScript. This has the advantage that you can now emit signals with arguments using a variadic function, and you also no longer need to specify `owner->` but has the disadvantage that this function must never be used if the owner type doesn't derive from `Object` (although you should get a nice compile error about the type not having emit_signal, but likely IDE's won't notice that). I suppose you need to make a call on whether this is ok or not. 

I will open a PR and you can give any further suggestions, change requests, amendments etc there.

[1] https://github.com/danielytics/godot-cpp/commit/b6b817a0f59ee75e09eee50b0f22414e4ea6385a

**Comment by danielytics** [comment]
Closing as this has served its purpose. Any additional discussion would probably be easier in the PR now.
