### ISSUE TITLE
nativescript-1.1 register_property

### ISSUE THREAD

**Issue by thankjura** [GodotNativeTools/godot-cpp#114]
can't compile register_property
code:
`
register_property<Shell, double> ("timeout", &Shell::_TIMEOUT, double(5.0));
`
works in master,

but can't compile with nativescript-1.1 branch:

![image](https://user-images.githubusercontent.com/2144212/37259218-90fbc474-2594-11e8-8f2d-6d950542d9c9.png)

How to export double or int type?

**Comment by karroffel** [comment]
Hmmmmm that is very weird, I didn't think I broke that. Let me take a look

**Comment by karroffel** [comment]
Oh okay, I *did* break it. Huh.

**Comment by karroffel** [comment]
Pushed a commit, did it fix this issue for you?

**Comment by thankjura** [comment]
Yes. Thanks
