### ISSUE TITLE
PATH environment

### ISSUE THREAD

**Issue by thankjura** [GodotNativeTools/godot-cpp#117]
Can't compile godot-cpp:

$ make linux64 USE_CLANG=yes REGENERATE_BINDINGS=yes GODOT_BIN_PATH=/usr/bin/godot.x11.tools.64.llvm
> scons: Reading SConscript files ...
> OpenGL ES 3.0 Renderer: GeForce GTX 1070/PCIe/SSE2
> scons: done reading SConscript files.
> scons: Building targets ...
> clang++ -o src/core/Dictionary.o -c -fPIC -g -O3 -std=c++14 -Wwrite-strings -m64 -I. -I/home/GrandMaster/Development/games/godot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Dictionary.cpp
> sh: clang++: command not found
> clang++ -o src/core/GodotGlobal.o -c -fPIC -g -O3 -std=c++14 -Wwrite-strings -m64 -I. -I/home/GrandMaster/Development/games/godot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/GodotGlobal.cpp
> sh: clang++: command not found
> clang++ -o src/core/Array.o -c -fPIC -g -O3 -std=c++14 -Wwrite-strings -m64 -I. -I/home/GrandMaster/Development/games/godot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Array.cpp
> scons: *** [src/core/Dictionary.o] Error 127
> sh: clang++: command not found
> clang++ -o src/core/PoolArrays.o -c -fPIC -g -O3 -std=c++14 -Wwrite-strings -m64 -I. -I/home/GrandMaster/Development/games/godot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/PoolArrays.cpp
> scons: *** [src/core/GodotGlobal.o] Error 127
> scons: *** [src/core/Array.o] Error 127
> sh: clang++: command not found
> scons: *** [src/core/PoolArrays.o] Error 127
> scons: building terminated because of errors.
> make: *** [Makefile:28: linux64] Ошибка 2
> 

$ where clang++
> /usr/lib/llvm/6/bin/clang++

I add this patch:
https://github.com/sh44/godot-cpp/commit/d4316a387aef57713b6863f54484f670e1ebc7e4

and now compile fine compile

**Comment by karroffel** [comment]
If @sh44 is okay with it then I could make a pull request and apply those changes. The gcc-5 thing is an error anyway and adding the PATH seems like a good idea as well.

**Comment by BastiaanOlij** [comment]
The scons file has changed a lot since April thanks to a number of people happily working on Linux. Seeing there hasn't been further discussion I'm closing this. Please feel free to re-open if this is still an outstanding issue. If the fix is still valid a PR would be greatly appreciated.
