### ISSUE TITLE
How to cast scene to custom class

### ISSUE THREAD

**Issue by thankjura** [GodotNativeTools/godot-cpp#119]
Ref<PackedScene> scene = ResourceLoader::get_singleton()->load("res://bullet.tscn");
Node2D* bullet = (Node2D*) scene.ptr()->instance();
get_tree()->get_current_scene()->add_child(bullet); // it works fine

Bullet* b = (Bullet*) bullet;
printf("bullet->get_data(): %d\n", b->get_data()); // bad

in output:
33, but expected 99, see demo project

[bug-cpp1.zip](https://github.com/GodotNativeTools/godot-cpp/files/1872580/bug-cpp1.zip)

**Comment by thankjura** [comment]
thanks ;)

**Comment by karroffel** [comment]
Oh also as a side note: when you have a `Ref<T> x` then you don't need to do `x.ptr()->method();`. You can do `x->method();` directly because overloading `operator ->` allows for this :)

**Comment by thankjura** [comment]
good, thanks ;)
