### ISSUE TITLE
Cannot compile/create `libtest.so`

### ISSUE THREAD

**Issue by JonErikDSuero** [GodotNativeTools/godot-cpp#125]
Hi,

I'm following the README.
However `clang -o lib/libtest.so -shared src/init.os -L../godot-cpp/lib -lgodot-cpp` gives me the following two errors:
```
ld: warning: directory not found for option '-L../godot-cpp/lib'
ld: library not found for -lgodot-cpp
```

The `../godot-cpp/lib`directory does not exist.
Did I forget to do something?

Thanks!

**Comment by thankjura** [comment]
godot-cpp/bin/libgodot-cpp.a is exist?

**Comment by JonErikDSuero** [comment]
@thankjura Yup, I have `godot-cpp/bin/libgodot-cpp.a`.

Apparently, this tutorial worked for me: https://gamedevadventures.posthaven.com/using-c-plus-plus-and-gdnative-in-godot-part-1

I'm going to close this issue for now. I'm not exactly sure why the tutorial worked, and not the README. The main difference is the `SConstruct`.

**Comment by t-mullen** [comment]
Some versions of `ld` require a different naming convention for the `-l` option. Try removing `lib` from the beginning of the name and `.a` from the end.

So instead of:
```
clang -o bin/libtest.so -shared src/init.os -Lgodot-cpp/bin -llibgodot-cpp.osx.debug.64.a
```
Do:
```
clang -o bin/libtest.so -shared src/init.os -Lgodot-cpp/bin -lgodot-cpp.osx.debug.64
```
