### ISSUE TITLE
Error : /bin/ld: cannot find -lgodot_cpp_bindings

### ISSUE THREAD

**Issue by kakoeimon** [GodotNativeTools/godot-cpp#137]
I cannot use godot-cpp cause I get this error when I compile (f.e) the SimpleDemo.

**Comment by karroffel** [comment]
The name of the library is different, check the `bin/` folder of the C++ bindings. On my machine I have a file `libgodot-cpp.linux.64.a`, so when compiling the SimpleDemo I need to use `-lgodot-cpp.linux.64` instead.

**Comment by kakoeimon** [comment]
@karroffel I replaced the 
`env.Append(LIBS=['godot_cpp_bindings'])
with
`env.Append(LIBS=['godot-cpp.linux.64'])

and now it compiles. Thanks.
