### ISSUE TITLE
Exported properties are reseted when the "Node" is used as a plugin object.

### ISSUE THREAD

**Issue by kakoeimon** [GodotNativeTools/godot-cpp#143]
When we register a class with godot::register_tool_class and set this as the node of a plugin, the exported properties get reseted when we save, close and reload a scene that it uses the plugin node.
Cause the matter is little bit complicated I created a sample project to demonstrate the problem.
[SimpleDemo_Export.zip](https://github.com/GodotNativeTools/godot-cpp/files/2083317/SimpleDemo_Export.zip)
It's only compiled and setted to be used in linux 64bit (experienced users will be able to compile and set it in any platform, I guess).
Here we have in main.tscn (the default one) a node Simple which is a gdns node that is is registered with godot::register_class (it exist cuase I was making other tests).
Other node is a gdns node that it is registered with godot::register_tool_class
Simple_Cpp is a node that it is an Other node but it was added by using the plugin Simple_Cpp_Plugin (this is the problematic one).
Simple_Node is a node that it was added by the plugin Simple_Plugin and it is a pure gdscript node (it exists to present that the correct functionality is to keep the changes of an exported property).

All those nodes contain an exported property that it is named Value and it is an int. As you can see, Simple, Other and Simple_Node have keeped the changed value.
Try to change the value of the Simple_Cpp, and then save, close the scene and reload it.
The changed value of the Simple_Cpp is reseted to 0.

I do not know if this issue is a godot-cpp or GDNative problem.
All tests are made with NativeScript 1.0 and Godot 3.0.2 in Linux 64bit (Manjaro)

**Comment by karroffel** [comment]
Does the same happen with GDScript? Because I think that exported values in tool scripts are not saved anyway (and if at all it would be in the project settings).

**Comment by kakoeimon** [comment]
@karroffel I included in the example a plugin that creates a node that uses gdscript (Simple_Node from Simple_Plugin) to demonstrate that the correct behavior is to keep the changes.

**Comment by kakoeimon** [comment]
@karroffel the changed values of the exported properties are stored in the .tscn file of the Scene that contains the instanced files. In the example are stored in the main.tscn and the changed property (value) of the Simple_Cpp is stored in there.

**Comment by kakoeimon** [comment]
@karroffel it looks like that the changed property in the Simple_Cpp is stored in the wrong line. It is stored before the :
`
script = ExtResource( 3 )
__meta__ = {
"_editor_icon": ExtResource( 4 )
}
'
and it needs to be stored after it.

I changed the position of the value in the .tscn file with a text editor and now it looks like that it works as expected.

**Comment by karroffel** [comment]
Ah, this has been fixed. Can you try a recent master build?

**Comment by kakoeimon** [comment]
@karroffel will try. It will take some time.

**Comment by kakoeimon** [comment]
@karroffel it is fixed in master. Thanks.
