### ISSUE TITLE
use gdnative_wrapper instead?

### ISSUE THREAD

**Issue by pgruenbacher** [GodotNativeTools/godot-cpp#146]
I think this repository is no longer necessary as of 3.0.3 because there's a gdnative_wrapper=yes option when compiling godot. I believe you can just compile SimpleLibrary using the generated library at that point.
@karroffel would you say the godot-cpp and godot_headers is meant to allow people to develop without cloning the entire engine repo, but if people were wanting to use the most up-to-date code, they'd just use the engine's gdnative_wrapper option when compiling?

**Comment by karroffel** [comment]
That's not how it works :)

I wrote a rather technical article about the GDNative architecture [here](https://godotengine.org/article/look-gdnative-architecture).

It mentions this

> The library can then access the needed functions from that struct. Practically that means that instead of writing `godot_some_function();` it would be `api->godot_some_function();`.

> Some people prefer to simply write function names instead of accessing them via a struct, so when needed Godot's build system can generate a static library that wraps all the function pointers into static functions with the same name.

So no, this repository is still needed. It has all the C++ wrappers, all the convenience functionality etc. The `gdnative_wrapper` just creates a library that translates direct function calls into the corresponding "api struct" calls
