### ISSUE TITLE
Crash while instantiating scene using NativeScript 1.1

### ISSUE THREAD

**Issue by eligt** [GodotNativeTools/godot-cpp#166]
It seems that ___make_wrapper_function calls godot_free instead of godot_alloc, almost as if the wrong pointer is set in the godot_gdnative_core_api_struct

I tried cleaning, re-checking out repos, regenerating api.json and rebuilding everything with the same result. Attaching full [backtrace](https://github.com/GodotNativeTools/godot-cpp/files/2260561/backtrace.txt).

**Comment by eligt** [comment]
Note: this happens while registering a method using the register_method() function

**Comment by eligt** [comment]
Of course, the second I post this I realize the issue. Just copying the file "gdnative_api_struct.gen.h" from `godot/modules/gdnative/include` to `godot-cpp/godot_headers` seem to have fixed it. I thought this was part of some of the automated processes but maybe it isn't?

**Comment by BastiaanOlij** [comment]
godot_headers now contains an updated gdnative_api_struct.gen.h so updating the submodule should resolve this.
