### ISSUE TITLE
Merging NativeScript 1.1

### ISSUE THREAD

**Issue by BastiaanOlij** [GodotNativeTools/godot-cpp#173]
Hi All,

Karroffel and I were discussing merging nativescript 1.1 into master. We feel it's ready to do this. I've been building a fairly complex module (https://github.com/BastiaanOlij/gdprocmesh) with it and so far it's been pretty solid and it would be good to merge it now before the nativescript and master branch start growing apart again.

But as others may be in the mids of things I don't want to suddenly throw this on people so please provide some feedback and if there are no objections we'll probably merge it next weekend (25th of Aug)

**Comment by SG7** [comment]
Great work Guys! I would love to see it merged soon!
A small question though: Are any of the open 24 issues road blockers?
I would be nice to squash at least some of them.

**Comment by BastiaanOlij** [comment]
@SG7 I think most of those have been reported against the master branch, some of them will probably be fixed by the nativescript work. I think we should re-evaluate each once everything is merged and people can test their work

**Comment by Redwan13** [comment]
Is there anywhere comprehensive changelist of nativescript 1.1?

**Comment by fire** [comment]
Ping! I had to merge this manually in my fork. Wanted to know the current status.

**Comment by BastiaanOlij** [comment]
Merged by #194 !
