### ISSUE TITLE
Pool*Array::clear() not bound

### ISSUE THREAD

**Issue by karroffel** [GodotNativeTools/godot-cpp#18]
In fact, they C API is missing those functions.

**Comment by RameshRavone** [comment]
I guess this too. Must be closed.

**Comment by karroffel** [comment]
Well it's not fixed yet.

**Comment by karroffel** [comment]
I'm not sure why I opened this issue, the `PoolVector<T>` class in Godot doesn't have a `clear()` method, so yey?
