### ISSUE TITLE
Crash on `register_property` with Resources

### ISSUE THREAD

**Issue by clayjohn** [GodotNativeTools/godot-cpp#188]
When you try to export a property to be accessed in GDscript using `register_property` it crashes the game if the property happens to be a Resource type (I have encountered this with Path3D, Curve3D, and SurfaceTool). 

For example
```
register_property<ClassName, Ref<SurfaceTool>>("surface_tool", &ClassName::surface_tool, Ref<SurfaceTool>());
```
I have identified the last argument as the source of the error. No matter the value passed it will crash the game, even if Null is passed. 

This is closely connected to issue #156 . The issue there is that in order to use Resources you have to first define the resource and then call `.instance()` on it. Failing to do so will crash the game when you run it without giving an error. For example
```
Ref<SurfaceTool> st = Ref<SurfaceTool>();
```
Will run fine, but will crash if any method of SurfaceTool is called. 
But, 
```
Ref<SurfaceTool> st;
st.instance();
```
works perfectly. This seems to be intended behavior for defining and using Resources in GDNative. However, because of this implementation there is no way to call instance before exporting the property so if you try the game will crash.

**Comment by clayjohn** [comment]
So, by overriding `_get_property_list` I can avoid having to register the resources in `_register_methods`?

**Comment by BastiaanOlij** [comment]
Well I use that for entirely different reasons, just giving it as an example that properties can work with references. Still need to look into why it doesn't seem to work with _register_methods, it should in the same way.
