### ISSUE TITLE
Unknown attribute PathIsDir

### ISSUE THREAD

**Issue by BastiaanOlij** [GodotNativeTools/godot-cpp#211]
Looks like Will's SConstruct changes does have a small fault:

```
AttributeError: '_PathVariableClass' object has no attribute 'PathisDir':
  File "C:\Users\basti\Development\My tutorials\gdnative_cpp_example\godot-cpp\SConstruct", line 34:
    opts.Add(PathVariable('headers_dir', 'Path to the directory containing Godot headers', 'godot_headers', PathVariable.PathisDir))
```

@willnationsdev  :)

Personally seeing this is now a submodule I would say, get rid of it :)

**Comment by BastiaanOlij** [comment]
Ok, that one is a case error, its PathIsDir with capital I.

After fixing that I get:
```
AttributeError: 'builtin_function_or_method' object has no attribute 'UnknownVariables':
  File "C:\Users\basti\Development\My tutorials\gdnative_cpp_example\godot-cpp\SConstruct", line 39:
    unknown = vars.UnknownVariables()
```

**Comment by BastiaanOlij** [comment]
And that is just ```vars.UnknownVariables``` should be ```opts.UnknownVariables```

Now its just not treating custom_api_file as an optional parameter but a mandatory one..

**Comment by BastiaanOlij** [comment]
Ok fixed, it all, PR coming

**Comment by willnationsdev** [comment]
Lol, wow. Looks like I missed the party. I hadn't quite gotten a chance to test the changes yet, so I'm sorry about that.

**Comment by BastiaanOlij** [comment]
That's why we help each other out :)
