### ISSUE TITLE
Ref<Material> compile-time error

### ISSUE THREAD

**Issue by lupoDharkael** [GodotNativeTools/godot-cpp#219]
When I try to create a Ref\<Material> the compiler shows the following error:

```
In file included from godot-cpp/include/core/Godot.hpp:12,
                 from src/init.cpp:1:
godot-cpp/include/core/Ref.hpp: In instantiation of 'void godot::Ref<T>::instance() [with T = godot::Material]':
src/TestClass.hpp:22:21:   required from here
godot-cpp/include/core/Ref.hpp:190:3: error: no matching function for call to 'godot::Ref<godot::Material>::ref(godot::Resource*)'
   ref(T::_new());
   ^~~
godot-cpp/include/core/Ref.hpp:17:7: note: candidate: 'void godot::Ref<T>::ref(const godot::Ref<T>&) [with T = godot::Material]'
  void ref(const Ref &p_from) {
       ^~~
godot-cpp/include/core/Ref.hpp:17:7: note:   no known conversion for argument 1 from 'godot::Resource*' to 'const godot::Ref<godot::Material>&'
```

I found it because of an error in `set_material_override` of MeshInstance, I instanced a Ref\<ShaderMaterial> (that class doesn't get a compilation error) but when I tried to set the material to a MeshInstance the project would crash and show a backtrace.

I supposed it was related with Ref\<Material> because that's the type `set_material_override` receives. I may be wrong and they could be unrelated errors.

I'm providing a reproduction project, just drop godot-cpp with the bindings compiled in bin/ and call ùse the makefile.
The important code is in src/TestClass.hpp
[report-material.zip](https://github.com/GodotNativeTools/godot-cpp/files/2645709/report-material.zip)

**Comment by bruvzg** [comment]
```c++
MeshInstance *meshInst = new MeshInstance;
```
`new` won't work with gdnative objects, use `_new` static method instead:
```c++
MeshInstance *meshInst = MeshInstance::_new();
```
and `meshInst->free();` to delete it.

**Comment by bruvzg** [comment]
Also `Material` is [pure virtual class](https://github.com/godotengine/godot/blob/master/scene/register_scene_types.cpp#L579) and can't be instanced (doesn't have `_new()` method).

**Comment by lupoDharkael** [comment]
Interesting, I didn't know about these changes in the API. I guess this can be closed.

**Comment by karroffel** [comment]
The underscore is because `new` is a keyword in C++ and you can't have a method named like that

**Comment by karroffel** [comment]
There was a time where we used an overload for `operator new` but that turned out to be quite problematic :/
