### ISSUE TITLE
Compiling the bindings on windows crashes with scons

### ISSUE THREAD

**Issue by 2shady4u** [GodotNativeTools/godot-cpp#228]
Hello everyone,

I'm using a custom build of Godot (v3.1 beta2) and the latest master of the godot-cpp repo.
I have create the api.json as requested in the tutorial and I'm trying to compile the bindings as such:

`scons platform=windows generate_bindings=yes use_custom_api_file=yes custom_api_file=../api.json`

This starts up the compilation process and subsequently crashes at the 'ResourceFormatLoader.cpp'-file.
I have checked the error, but have no clue how to fix this.

`cl /Fosrc\gen\ResourceFormatImporter.obj /c src\gen\ResourceFormatImporter.cpp /TP /nologo /EHsc /D_DEBUG /MDd /I. /Igodot_headers /Iinclude /Iinclude\gen /Iinclude\core
ResourceFormatImporter.cpp
cl /Fosrc\gen\ResourceFormatLoader.obj /c src\gen\ResourceFormatLoader.cpp /TP /nologo /EHsc /D_DEBUG /MDd /I. /Igodot_headers /Iinclude /Iinclude\gen /Iinclude\core
ResourceFormatLoader.cpp
src\gen\ResourceFormatLoader.cpp(42): error C2059: syntax error: ''
scons: *** [src\gen\ResourceFormatLoader.obj] Error 2
scons: building terminated because of errors.`

Is this a known problem?

**Comment by karroffel** [comment]
Yes, this is known and should be an easy fix, just needs someone to be done.

https://github.com/godotengine/godot/issues/25006

I don't have a dev environment set up for this here, but adding the `"typename"` here should fix it

https://github.com/GodotNativeTools/godot-cpp/blob/262d53c05eea71655e59c836c382b908b6fd9d38/binding_generator.py#L814

**Comment by arimus** [comment]
@karroffel that fix does indeed appear to work. I've just submitted a pull request for it.
