### ISSUE TITLE
GDNative doesn't work with Server and Heardless Version of Godot 3.1

### ISSUE THREAD

**Issue by ricardoalcantara** [GodotNativeTools/godot-cpp#234]
How to replicate.

clone BastiaanOlij's GDNative example:
`git clone --recursive https://github.com/BastiaanOlij/gdnative_cpp_example.git`

Build godot-cpp
`scons -j 8 platform=linux generate_bindings=yes bits=64`

Build the source
`scons -j 8 platform=linux`

Open Godot 3.1 and run the **demo** for the first time (I have to reconnect the signal from that example)
then try both Server or Headless versions:

```
$ godot31-server 
ERROR: init_library: Condition ' lib_path.length() == 0 ' is true.
   At: modules/gdnative/nativescript/nativescript.cpp:1474.
ERROR: connect: Condition ' !signal_is_valid ' is true. returned: ERR_INVALID_PARAMETER
   At: core/object.cpp:1463.

$ godot31-headless 
ERROR: init_library:  does not have a library for the current platform
   At: modules/gdnative/nativescript/nativescript.cpp:1474.
ERROR: connect: In Object of type 'Sprite': Attempt to connect nonexistent signal 'position_changed' to method 'Node._on_Sprite_position_changed'
   At: core/object.cpp:1463.

```

**Comment by bruvzg** [comment]
Server/Headless builds are separate `Server` platform, you should to add `Server.64="res://bin/x11/libgdexample.so"` line to `[entry]` section of `gdexample.gdnlib`

**Comment by ricardoalcantara** [comment]
I didn't know that. Sorry for open so many issues that is not actually issues. Maybe documentation issues.
