### ISSUE TITLE
How to set a material on a mesh?

### ISSUE THREAD

**Issue by mnn** [GodotNativeTools/godot-cpp#238]
In C# there is a method `SurfaceSetMaterial`, in GDScript `surface_set_material`. Since C++ misses this, I thought it's because overriding of `=` operator in Ref and so one should use `surface_get_material` and assign a new value into the Ref.

This snippet
```cpp
          const char *posStr = chunkPos.format().c_str();
          int64_t sc = mesh->get_surface_count();
          Material *surfMatBefore = mesh->surface_get_material(0).ptr();
          mesh->surface_get_material(0) = material;
          Material *surfMatAfter = mesh->surface_get_material(0).ptr();
          Godot::print(
              "Setting mat for non-empty mesh for chunk {0} (sc = {1}, surf_mat_bef = {2}, surf_mat_aft = {3}, mat = {4})",
              posStr, sc, surfMatBefore, surfMatAfter, material.ptr()
          );
```
produces following output:
> Setting mat for non-empty mesh for chunk (2, 0, 1) (sc = 1, surf_mat_bef = Null, surf_mat_aft = Null, mat = [SpatialMaterial:1125])

I am quite confused, `material` has a value, is assigned to surface mat. Ref (which I thought handles assignment on its own), why it's still null after assignment? How should one set a surface material of a mesh?

**Comment by bruvzg** [comment]
`Mesh` is virtual class and doesn't have `surface_set_material` neither in C++ nor in GDScript.

`ArrayMesh` have `surface_set_material` method.

You should be able cast `Ref<Mesh> mesh` to `ArrayMesh`:

```c++
ArrayMesh *amesh = cast_to<ArrayMesh>(*mesh);
amesh->surface_set_material(idx, material);
```

**Comment by mnn** [comment]
Oh, I totally overlooked that (I probably wrongly assumed Mesh material can be changed), sorry for a stupid question...

Thank you very much.
