### ISSUE TITLE
Error building under OS X in debug mode 

### ISSUE THREAD

**Issue by Antokolos** [GodotNativeTools/godot-cpp#245]
Attempt to build under OS X Yosemite produces the following result:

bash-3.2$ scons headers="godot_headers" platform=osx bits=64 generate_bindings=yes
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o src/core/AABB.o -c -g -std=c++14 -arch x86_64 -Og -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/AABB.cpp
error: invalid integral value 'g' in '-Og'
error: invalid integral value 'g' in '-Og'
scons: *** [src/core/AABB.o] Error 1
scons: building terminated because of errors.`

If building in release mode (i.e. supplying target=release), then this error is not produced and build goes fine

**Comment by karroffel** [comment]
@BastiaanOlij you're the OS X expert here, any idea what flags have to be used here instead?

**Comment by BastiaanOlij** [comment]
expert.. expert... not really :)

Looks like the settings were just copied from the linux build. I'm guessing -Og  isn't a valid switch.
Looking at godots own compilation I think the switch on osx is -g1 

I can try later if I don't forget but I think this line of code needs to change:
https://github.com/GodotNativeTools/godot-cpp/blob/master/SConstruct#L92
