### ISSUE TITLE
Can operators be override? 

### ISSUE THREAD

**Issue by xDGameStudios** [GodotNativeTools/godot-cpp#246]
Wanted to know if there possibility to override the operators ">" "<" "!=" from the C++ side to the GDscript API?!

**Comment by karroffel** [comment]
No, there is no way to override operators so that they are usable from GDScript.

That's a limitation with how GDScript and Godot handles operators, so there is not really a way to fix that without modifications to Godot.

**Comment by xDGameStudios** [comment]
Sadly... but thank you for the answer
