### ISSUE TITLE
How to pass a custom class GDNative -> GDScript?

### ISSUE THREAD

**Issue by xDGameStudios** [GodotNativeTools/godot-cpp#249]
Right now I'm making a wrapper library for a c++ Graph library using NativeScript.
For wrapping the third-party library I'm creating a `Graph` class extending `Reference` that contains inside it a reference to the third-party graph.

now I also have `Vertex` and `Arc` (also extending `Reference`). When I do `my_graph.add_vertex()` this methods needs to return `Vertex` how should I do this?! What would be the `add_vertex()` return type?!

`Vertex *add_vertex();` -> return vertex

or 

`Variant add_vertex();` -> returning Variant(vertex)

or do I need to do another thing?!
This is more of a Question not an issue with the code!

**Comment by karroffel** [comment]
If the `Vertex` type is defined as a "GDNative class inheriting Reference" then you should be able to return `Vertex *` or `Ref<Vertex>`

**Comment by xDGameStudios** [comment]
It is and I'm doing it right now... just wanted to confirm :)
one more thing though.. the third party lib when I fetch and vertex by id (number) it returns a CVertex that I wrap in my `Vertex`(extending Reference) class.. what happens is that I create a new instance of `Vertex` and store the `CVertex` inside but then in the GDScript side I can't really do stuff like.

`graph.get_vertex(0) == graph.get_vertex(0)`  -> this returns false because they are different Object that contain the same `CVertex` reference inside. :(

So I was trying to store some kind of `map<CVertex, Vertex*>` (CVertex, pointer to Vertex) that I could use to check if the pointer is still valid return the same instance... instead of creating a new one. Don't know if my approach makes sense at all, though.

**Comment by kohlten** [comment]
@karroffel would this be possible in the C API?

If so, could you provide a basic example?

Thank you,
Alex

**Comment by karroffel** [comment]
Yes. In that case you need to deal with the `godot_variant` API to get custom data out of the Variant and construct a Variant with the object that has the user-script attached to it.

An example would be quite long to write as the C API is really verbose. You can basically translate all the contructors and casts into the C functions. I don't have the time at the moment to write up example code for this, sorry.
