### ISSUE TITLE
How to instantiate custom class via GDNative (Question)

### ISSUE THREAD

**Issue by xDGameStudios** [GodotNativeTools/godot-cpp#253]
What is the correct way to instantiate a custom class and return it to Godot via GDNative?!

(minimal representation below)

```
class A : public Reference {
     Ref<B> create_b()
}

class B : public Reference {
}
```

what should be the body of `create_b()` ?
for future reference the correct way to do this is:

`return Ref<B>::__internal_constructor(B::_new())` ;)

**Comment by follower** [comment]
As of ~ 9eceb16f0553884094d0f659461649be5d333866 the `__internal_constructor()` workaround should no longer be necessary and use of it may lead to crash, this should now work correctly:

   * `Ref<CustomClass> ref = Ref<CustomClass>(custom_class_instance);`

See #417 for more details.
