### ISSUE TITLE
String get_data returns random string

### ISSUE THREAD

**Issue by WesleiRamos** [GodotNativeTools/godot-cpp#255]
I'm working in "discord richpresence" for godot, sometimes when I get app_id value from dictionary is the right value but in the most cases is the wrong value, honestly I don't know what is happening, in previous versions (3.0 to be exact) the code works as expected.

![](https://i.imgur.com/099ugxj.png)

The code is basicaly
```gd
gdnative.init({ "app_id": "345229890980937739" })
```

```c++
void RichPresence::init(Dictionary initialize) {
	...
	const char* appId = ((String)initialize["app_id"]).ascii().get_data();
	printf("--> %s , %s <-- \n", appId, (String)initialize["app_id"]);
	...
}
```
full code: https://github.com/WesleiRamos/Godot-Rich-Presence/blob/master/src/richpresence.cpp#L105

I'm using Godot on windows 10, sorry for my english 👍

**Comment by karroffel** [comment]
I'm not 100% sure how the C++ deallocation rules work, but can you try saving the result of `.ascii()` in a variable?

Godot Strings are not guaranteed to be utf8/ascii, also they generally do not end with a `NUL` terminator. That's why the `.ascii()` and `.utf8()` calls return a `CharString`, which "owns" the temporary allocation.

Can you try doing this?

```cpp
CharString appIdBuf = ((String) initialize["app_id"]).ascii();
const char *appId = appIdBuf.get_data();
printf(...);
```

This might be the problem.

**Comment by WesleiRamos** [comment]
> I'm not 100% sure how the C++ deallocation rules work, but can you try saving the result of `.ascii()` in a variable?
> 
> Godot Strings are not guaranteed to be utf8/ascii, also they generally do not end with a `NUL` terminator. That's why the `.ascii()` and `.utf8()` calls return a `CharString`, which "owns" the temporary allocation.
> 
> Can you try doing this?
> 
> ```c++
> CharString appIdBuf = ((String) initialize["app_id"]).ascii();
> const char *appId = appIdBuf.get_data();
> printf(...);
> ```
> 
> This might be the problem.

Ok, this solves the problem, thanks!

**Comment by 3ddelano** [comment]
OMG! I was facing the same issue, this solution should be shown in the docs in bold as passing strings from GDScript to GDExtension is something trivial. Again, thanks for the response!
