### ISSUE TITLE
Signals registered from base class are not avialiabe for its sub-classes.

### ISSUE THREAD

**Issue by Geequlim** [GodotNativeTools/godot-cpp#26]
Register classes like this
```c++
class BaseClass : public GodotScript<Reference> {
    GODOT_SUBCLASS(BaseClass, Reference);
public:
    static void _register_methods() {

        register_signal<BaseClass>("my_signal");

        register_property("title", &BaseClass::title, String());
    }

    String title;
};

class SubClass : public  BaseClass {
    GODOT_SUBCLASS(SubClass, BaseClass);
};

/** NativeScript Initialize **/
NATIVESCRIPT_INIT() {
    register_class<BaseClass>();
    register_class<SubClass>();
}
```
It can't work in GDScript
```gdscript
func _ready():
    var script = NativeScript.new()
	script.library = load("res://nativelib.tres")
	script.class_name = "SubClass"

	var inst = script.new()
	inst.connect("my_signal", self, "_callback")

func _callback():
    print("-----------")
```

**Comment by RameshRavone** [comment]
This is happening because the signal's are registered to the BaseClass reference, may be we can somehow register the signals from BaseClass into SubClass when instancing.

**Comment by karroffel** [comment]
This should work, maybe it's a bug in the module, if it's in the bindings then it should be easy to fix. Will take a look at this later

**Comment by karroffel** [comment]
https://github.com/godotengine/godot/blob/master/modules/nativescript/nativescript.cpp#L290

I think it might be because of that, I don't search for the base classes.

**Comment by karroffel** [comment]
@Geequlim can you update your Godot build and test if this still is a problem?

**Comment by Geequlim** [comment]
Yes I wiil have a try tomorrow

2017年7月30日 21:55，"Thomas Herzog" <notifications@github.com>写道：

**Comment by RameshRavone** [comment]
We better close this,
