### ISSUE TITLE
::_new() not creating an object to be referenced

### ISSUE THREAD

**Issue by rpanuski** [GodotNativeTools/godot-cpp#280]
I'm working with GODOT for a project and I'm attempting to create a mesh object and texture it via NativeScript 1.1 and C++.

I have done all of this in GDScript without any issues and attempting to move over to C++ is proving to be a bit of a headache.  Especially since the GODOT debugger doesn't seem to be registering anything before the application crashes.

My code is as follows:  (and does compile correctly)
//Instantiate Mesh
godot::MeshInstance *instance_;
instance_ = godot::MeshInstance::_new();
instance_->set_name(mesh_name);

The application crashes on the instance_->set_name call.  If I comment that line out, the application runs, but obviously nothing happens.

This also happens with the code below, when a function of MeshInstance is referenced in a different way.
//Instantiate Mesh
godot::MeshInstance *instance_;
godot::SphereMesh *mesh_;
instance_ = godot::MeshInstance::_new();
mesh_ = godot::SphereMesh::_new();
instance_->set_mesh(mesh_);

Any help would be appreciated.

Thanks!

**Comment by RameshRavone** [comment]
@rpanuski Is this one fixed for you, cause the problem seems to be either you forgot to add the _init() {} function or forgot to register_class.

If this is already fixed consider closing the issue

**Comment by 2shady4u** [comment]
I also confirm that this is a fixed issue and should be closed.
