### ISSUE TITLE
Quat multiplication is wrong

### ISSUE THREAD

**Issue by timower** [GodotNativeTools/godot-cpp#283]
The current implementation of Quat operator* just multiplies element wise.
Which is completely wrong, it should use the same implementation as the godot core.

**Comment by 2shady4u** [comment]
I've started a small pull request that rectifies this issue.
The implemented code was taken directly from the Godot master branch
and is, as a result, the one used for correct Quaternion multiplication.

The pull request can be found here: #289

**Comment by 2shady4u** [comment]
This should be fixed with PR #289

Could this be closed?

**Comment by karroffel** [comment]
Yes, sorry!
