### ISSUE TITLE
Generating C++ bindings crashes due to syntax errors among others

### ISSUE THREAD

**Issue by 2shady4u** [GodotNativeTools/godot-cpp#287]
Building the C++ bindings on Windows with self-generated as well as default api.json gives back syntax errors. This was done using self-generated api.json's for both stable Godot v3.1 and v3.1.1
as well as using the supplied api.json present in the godot-cpp repository itself.

Branches for godot-cpp and godot-headers were the 3.1 ones.

command (with or without the use_custom_api_file-flag):
`scons platform=windows bits=64 generate_bindings=yes use_custom_api_file=yes custom_api_file=../api.json`

Crash for self-generated api's:
`cl /Fosrc\gen\AudioEffectSpectrumAnalyzer.obj /c src\gen\AudioEffectSpectrumAnalyzer.cpp /TP /nologo /EHsc /D_DEBUG /MDd /I. /Igodot_headers /Iinclude /Iinclude\gen /Iinclude\core
AudioEffectSpectrumAnalyzer.cpp
c:\users\default\native-test\godot-cpp\include\gen\AudioEffectSpectrumAnalyzer.hpp(35): error C3646: 'get_fft_size': unknown override specifier
c:\users\default\native-test\godot-cpp\include\gen\AudioEffectSpectrumAnalyzer.hpp(35): error C2059: syntax error: '('
c:\users\default\native-test\godot-cpp\include\gen\AudioEffectSpectrumAnalyzer.hpp(35): error C2238: unexpected token(s) preceding ';'
src\gen\AudioEffectSpectrumAnalyzer.cpp(61): error C2039: 'FFT_Size': is not a member of 'godot::AudioEffectSpectrumAnalyzer'
c:\users\default\native-test\godot-cpp\include\gen\AudioEffectSpectrumAnalyzer.hpp(16): note: see declaration of 'godot::AudioEffectSpectrumAnalyzer'
src\gen\AudioEffectSpectrumAnalyzer.cpp(61): error C2039: 'get_fft_size': is not a member of 'godot::AudioEffectSpectrumAnalyzer'
c:\users\default\native-test\godot-cpp\include\gen\AudioEffectSpectrumAnalyzer.hpp(16): note: see declaration of 'godot::AudioEffectSpectrumAnalyzer'
src\gen\AudioEffectSpectrumAnalyzer.cpp(61): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
src\gen\AudioEffectSpectrumAnalyzer.cpp(61): error C2146: syntax error: missing ';' before identifier 'get_fft_size'
src\gen\AudioEffectSpectrumAnalyzer.cpp(61): error C2143: syntax error: missing ';' before '{'
src\gen\AudioEffectSpectrumAnalyzer.cpp(61): error C2447: '{': missing function header (old-style formal list?)
scons: *** [src\gen\AudioEffectSpectrumAnalyzer.obj] Error 2
scons: building terminated because of errors.`

Crash when using the default api.json:
`src\gen\__init_method_bindings.cpp(683): error C2039: '___init_method_bindings': is not a member of 'godot::AudioEffectEQ6'
include\gen\AudioEffectEQ6.hpp(15): note: see declaration of 'godot::AudioEffectEQ6'
src\gen\__init_method_bindings.cpp(684): error C2039: '___init_method_bindings': is not a member of 'godot::AudioEffectDistortion'
c:\users\piet.bronders\documents\gitkraken\gloominc\godot-sqlite-dev\godot-cpp\include\gen\AudioEffectDistortion.hpp(16): note: see declaration of 'godot::AudioEffectDistortion'
src\gen\__init_method_bindings.cpp(685): error C2039: '___init_method_bindings': is not a member of 'godot::AudioEffectHighShelfFilter'
include\gen\AudioEffectHighShelfFilter.hpp(15): note: see declaration of 'godot::AudioEffectHighShelfFilter'
src\gen\__init_method_bindings.cpp(686): error C2039: '___init_method_bindings': is not a member of 'godot::AudioEffectPanner'
include\gen\AudioEffectPanner.hpp(15): note: see declaration of 'godot::AudioEffectPanner'
src\gen\__init_method_bindings.cpp(687): error C2039: '___init_method_bindings': is not a member of 'godot::AudioEffectBandPassFilter'
include\gen\AudioEffectBandPassFilter.hpp(15): note: see declaration of 'godot::AudioEffectBandPassFilter'
src\gen\__init_method_bindings.cpp(688): error C2039: '___init_method_bindings': is not a member of 'godot::AudioEffectNotchFilter'
include\gen\AudioEffectNotchFilter.hpp(15): note: see declaration of 'godot::AudioEffectNotchFilter'
src\gen\__init_method_bindings.cpp(689): error C2039: '___init_method_bindings': is not a member of 'godot::AudioEffectBandLimitFilter'
include\gen\AudioEffectBandLimitFilter.hpp(15): note: see declaration of 'godot::AudioEffectBandLimitFilter'
src\gen\__init_method_bindings.cpp(690): error C2039: '___init_method_bindings': is not a member of 'godot::AudioEffectStereoEnhance'
include\gen\AudioEffectStereoEnhance.hpp(15): note: see declaration of 'godot::AudioEffectStereoEnhance'
src\gen\__init_method_bindings.cpp(691): error C2039: '___init_method_bindings': is not a member of 'godot::AudioEffectEQ10'
include\gen\AudioEffectEQ10.hpp(15): note: see declaration of 'godot::AudioEffectEQ10'
src\gen\__init_method_bindings.cpp(692): error C2039: '___init_method_bindings': is not a member of 'godot::AudioEffectLowShelfFilter'
include\gen\AudioEffectLowShelfFilter.hpp(15): note: see declaration of 'godot::AudioEffectLowShelfFilter'
src\gen\__init_method_bindings.cpp(693): error C2039: '___init_method_bindings': is not a member of 'godot::AudioEffectChorus'
include\gen\AudioEffectChorus.hpp(15): note: see declaration of 'godot::AudioEffectChorus'
src\gen\__init_method_bindings.cpp(694): error C2039: '___init_method_bindings': is not a member of 'godot::AudioEffectDelay'
include\gen\AudioEffectDelay.hpp(15): note: see declaration of 'godot::AudioEffectDelay'
src\gen\__init_method_bindings.cpp(694): fatal error C1003: error count exceeds 100; stopping compilation
scons: *** [src\gen\__init_method_bindings.obj] Error 2
scons: building terminated because of errors.`

Seemingly the __init_method_bindings can't be found among other things... 

Does anyone know what to do?

**Comment by 2shady4u** [comment]
Seems that this is an issue of the godot-cpp 3.1 branch as the latest master branch doesn't have this issue.

**Comment by LATRio** [comment]
Godot 3.1 and 3.1.1 don't have fix for AudioEffectSpectrumAnalyzer's enums, so you have to wait for new stable's release.

**Comment by 2shady4u** [comment]
Oh well...
As this seems to be a known problem then, I'll close the issue.
