### ISSUE TITLE
register EditorPlugin

### ISSUE THREAD

**Issue by underdoeg** [GodotNativeTools/godot-cpp#290]
Is there already a way to extend the godot::EditorPlugin class and register custom node types via c++?

**Comment by karroffel** [comment]
Yes, instead of `register_class` you can do `register_tool_class` and then you can use the class inside the editor.

Be aware that if there is a tool class you should untick the `reloadable` as it can cause serious trouble.

**Comment by underdoeg** [comment]
Thanks. But how would I then register my custom EditorPlugin to the engine as a plugin?

**Comment by karroffel** [comment]
You do it the same way as you do with GDScript.

If you mean the `class_name` feature then you can select that in the gdns file.

**Comment by underdoeg** [comment]
Not sure if I understand correctly. I am looking for something like this:

```
class CustomPlugin : public godot::EditorPlugin {
GODOT_CLASS(CustomPlugin, godot::EditorPlugin)

public:
	void _enter_tree() {
		add_custom_type("CustomType", "Node", "some way to load the CustomType Class");
	}

	static void _register_methods() {
		register_method("_enter_tree", &WebcamPlugin::_enter_tree);
	}
};

class CustomType : public godot::Node {
GODOT_CLASS(CustomType, godot::Node)
}

extern "C" void GDN_EXPORT godot_nativescript_init(void *handle) {
	godot::Godot::nativescript_init(handle);

	godot::register_tool_class<CustomPlugin>();
	godot::register_tool_class<CustomType>();
}
```

**Comment by underdoeg** [comment]
Ah wait, I think I get it now. You create the plugin with gdscript and just add your gdns files as the custom types
