### ISSUE TITLE
Extend a GDNative class with GDScript

### ISSUE THREAD

**Issue by Flarkk** [GodotNativeTools/godot-cpp#291]
Hi everyone,

I've written a simple class named `Anchor` inherited from `Node` in GDNative.
My `Anchor` class properly loads and works from GDScript with `load("res://Anchor.gdns")`.
My ultimate goal is to have a GDScript class extend this `Anchor` class.
I expected the `class_name` attribute in the .gdns file would make my `Anchor` class appear in the "Add node" dialog, and then allow me to extend it, but it's not the case.
I've also tried the naive approch to directly extend the GDScript class with `extend "res://Anchor.gdns"` but it doesn't work (error message : "Could not load base class: res://Anchor.gdns").

Anyone can help ?

Here is the .gdns file :
```
[gd_resource type="NativeScript" load_steps=2 format=2]

[ext_resource path="res://bin/libtest.gdnlib" type="GDNativeLibrary" id=1]

[resource]
resource_name = "Anchor"
class_name = "Anchor"
library = ExtResource( 1 )
script_class_name = "Anchor"
script_class_icon_path = "res://icon.png"
```

And my `Anchor` class declaration and definition :
```C++
	class Anchor : public Node {
		GODOT_CLASS(Anchor, Node)

	public :
		static void _register_methods();
		void _init();	
		
		Anchor();
		~Anchor();
	};
```

```C++
void Anchor::_register_methods() {
    
}

void Anchor::_init() {

}

Anchor::Anchor() {
	
}

Anchor::~Anchor() {
	
}
```

**Comment by karroffel** [comment]
Unfortunately GDScript can only inherit from other GDScript files. That means You can't make a VisualScript base, a C# base or a NativeScript base.

There's not much we can do here :/

**Comment by Flarkk** [comment]
Thanks karroffel for your answer.
Hence I don’t understand the use of « class_name » in .gdns files. What’s the use case of it ?

**Comment by karroffel** [comment]
You can use the `class_name` feature to simple reference a NativeScript class.

For example you could make a `MapGenerator` class with the same name, then inside of GDScript you can do

```gdscript
var gen = MapGenerator.new()
``` 

instead of 

```gdscript
var gen = preload("res://path/to/map_generator.gdns").new()
```

**Comment by Flarkk** [comment]
What do you mean by
> an actual new Object type

Would my class need to _inherit_ Object ?
I guess this is the case for most Godot classes.
So if I understand well I could inherit `Node` for instance, and then I could put a GDScript on it ?

**Comment by Flarkk** [comment]
What do you mean by
> an actual new Object type

Would my class need to _inherit_ `Object` ?
As most Godot classes inherit `Object` it would mean I can inherit `Node` and then be able to put a GDScript on it.
Do I understand well ?

**Comment by Flarkk** [comment]
What do you mean by « _an actual new Object type_ » ?
Would my class _inherit_ Object ?
Not sure to get the subtility here since most Godot classes actually inherit Object

**Comment by Flarkk** [comment]
What do you mean by
> an actual new Object type

Would my class need to _inherit_ Object ?
I guess this is the case for most Godot classes.
So if I understand well I could inherit `Node` for instance, and then I could put a GDScript on it ?
