### ISSUE TITLE
binding_generator does not support current api.json file format

### ISSUE THREAD

**Issue by maxim-sheronov** [GodotNativeTools/godot-cpp#31]
At this moment enums in api file looks like "enum.Error"
`"return_type": "enum.Error",`

And it fails compilation of generated headers, row for example:
`class enum.Error;`

**Comment by karroffel** [comment]
I haven't added enum support yet, I need to do that sometime.. but of course if somebody wants to try and implement it: feel free to come to the IRC or write me a mail in case of any problems.

The binding_generator needs to detect if a type is an enum type or not, it also needs to generate the enums themselves, but overall it should be a rather easy task.

**Comment by maxim-sheronov** [comment]
@karroffel really I will try to fix it myself
