### ISSUE TITLE
Gdnative Singleton

### ISSUE THREAD

**Issue by piiertho** [GodotNativeTools/godot-cpp#311]
Hi there !

I have trouble implementing singleton pattern with GDNative.
I don't want to auto load, I really want godot to load a singleton by loading the gdns, without the need of extra configuration in editor.
[Here is the branch](https://github.com/utopia-rise/fmod-gdnative/tree/singletonGDNative)
The last commit on it enforce singleton pattern.
Here is gdns : 
```
[gd_resource type="NativeScript" load_steps=2 format=2]

[ext_resource path="res://lib/Fmod.gdnlib" type="GDNativeLibrary" id=1]

[resource]
resource_name = "Fmod"
class_name = "Fmod"
library = ExtResource( 1 )
script_class_name = "Fmod"
```
And gdnlib : 
```
[general]

singleton=true
load_once=true
symbol_prefix="fmod_"
reloadable=false

[entry]

Android.armeabi-v7a="res://lib/android/armeabi-v7a/libandroid_fmod_gdnative.so"
Android.arm64-v8a="res://lib/android/arm64-v8a/libandroid_fmod_gdnative.so"
X11.64="res://lib/linux/libGodotFmod.linux.so"
OSX.64="res://lib/osx/libGodotFmod.osx.dylib"
Windows.64="res://lib/windows/libGodotFmod.windows.dll"
iOS.armv7="res://lib/iOS/libGodotFmod.ios.a"
iOS.arm64="res://lib/iOS/libGodotFmod.ios.a"

[dependencies]

Android.armeabi-v7a=[ "res://lib/android/armeabi-v7a/libfmod.so", "res://lib/android/armeabi-v7a/libfmodstudio.so" ]
Android.arm64-v8a=[ "res://lib/android/arm64-v8a/libfmod.so", "res://lib/android/arm64-v8a/libfmodstudio.so" ]
X11.64=[  ]
Windows.64=[  ]
OSX.64=[  ]
iOS.armv7=[ "res://lib/iOS/libfmodstudio_iphoneos.a", "res://lib/iOS/libfmod_iphoneos.a", "res://lib/iOS/libgodot-cpp.ios.release.a" ]
iOS.arm64=[ "res://lib/iOS/libfmodstudio_iphoneos.a", "res://lib/iOS/libfmod_iphoneos.a", "res://lib/iOS/libgodot-cpp.ios.release.a" ]
```
When I try to call a method on it, engine tell: `Invalid call. Nonexistent function 'setSoftwareFormat' in base 'NativeScript'.`
It does it for every method.
What am I doing wrong ?

**Comment by karroffel** [comment]
The "singleton" field in the `gdnlib` file doesn't really do what you think it does.

All it does is that the engine will call `fmod_gdnative_singleton()` when the engine starts. The name is poor, I didn't like it at the time we introduced it, but it has nothing to do with "software singletons", sorry for that.

If you want something to act like a singleton you probably have to use the Autoload way of doing it.

**Comment by piiertho** [comment]
Thanks for the answer, Autoload will do the job, with a GDScript wrapper to autocomplete.
