### ISSUE TITLE
Handling void _input(InputEvent *e)  in C++

### ISSUE THREAD

**Issue by noobaldrin** [GodotNativeTools/godot-cpp#314]
How do you guys handle _input? I've seen it in gdscript it's like this:

```
func _input(event):
     if event is InputEventMouseMotion:
          # do something
```

I'm trying to implement _input in C++ this way:

In .hpp:
```
public:
void _input(InputEvent *event);
```

In .cpp:
```
register_method("_input", &Root::_input);
```

Implementation:
```
void Root::_input(InputEvent * event) {`
    if (dynamic_cast<InputEventMouseMotion*>(event))`
         // not gonna compile since event pointer is not polymorphic`
}
```

Any ideas?

**Comment by bruvzg** [comment]
Try using `cast_to` instead of `dynamic_cast`:
`InputEventMouseMotion *m = cast_to<InputEventMouseMotion>(p_event);`

**Comment by noobaldrin** [comment]
> Try using `cast_to` instead of `dynamic_cast`:
> `InputEventMouseMotion *m = cast_to<InputEventMouseMotion>(p_event);`
> 
> Here's working example of `_gui_input` in the gdnative module (look at the code without `GODOT_MODULE` defined, it's variant for the built-in module): https://github.com/bruvzg/godot_tl/blob/master/src/controls/tl_proto_control.cpp#L1147

Thanks. Will try this when I get home.

**Comment by hakuhan** [comment]
In gdextension. I will get "use undefined type godto::InputEvent" at ref.hpp
