### ISSUE TITLE
Bug: all kind of array(Array, PoolByteArray, PoolStringArray ...) Memory leak when pass to GdNative

### ISSUE THREAD

**Issue by zhangshiqian1214** [GodotNativeTools/godot-cpp#318]
**Godot version:**
Godot 3.1.1.stable.official and Godot v3.1.2.devel.custom_build

**OS/device including version:**
Windows7

**Issue description:**
Only create a lot of array in GDscript,  the memory can be freed.
Only create a lot of array in GDNative(cpp), the memory can be freed. 
But create a lot of array and PoolByteArray, PoolStringArray and so on, the memory can not be freed. And If the memory used more than device, the project will memory leak and crash.

![QQ截图20190805160317](https://user-images.githubusercontent.com/9353330/62448633-df41f880-b79a-11e9-9ac5-f5e8f9833f02.png)

**For now I use something like this:**
```GDscript
# test array
func _on_Button2_pressed():
	for i in range(10000):
		var data = []
		for j in range(1024):
			data.push_back(j)
		test.test_array(data)
	pass # Replace with function body.

```

**The project I tested**
[gdnative_test.zip](https://github.com/GodotNativeTools/godot-cpp/files/3466501/gdnative_test.zip)

**Comment by 2shady4u** [comment]
Heyo,

I ran your test example project and could not replicate these memory leaks.
This might've been fixed in a previous commit.

Could you check if this problem still persists? @zhangshiqian1214

**Comment by zhangshiqian1214** [comment]
OK, Today I clone new code, and this problem still persists. 
**Godot version:**
Godot 3.1.1.stable.official and Godot v3.1.2.devel.custom_build and v3.2.alpha.custom_build.a1033aea5

**OS/device including version:**
Windows7

**godot-cpp:**
master



**How to repeat:**
click the button "test array" some times. And you can see the memory rise and will not release.
You can click until you computer memory use up. And the same code in gdscript and no gdnative,
the memory will not rise.
I have try to debug in vs2017, but i just find array ref() is more than unref(). But i don't know how to fix this problem.

![1](https://user-images.githubusercontent.com/9353330/66934017-71ecf680-f06c-11e9-80a2-e78eb949b97c.png)
![2](https://user-images.githubusercontent.com/9353330/66934040-787b6e00-f06c-11e9-955d-1d200741aa5c.jpg)
![3](https://user-images.githubusercontent.com/9353330/66934050-7addc800-f06c-11e9-9ac6-14ccc32810fe.jpg)

**Comment by zhangshiqian1214** [comment]
I use #355 code and test ok, memory will not leak
