### ISSUE TITLE
GDNative version of GDScript's yield implementation 

### ISSUE THREAD

**Issue by ricardoalcantara** [GodotNativeTools/godot-cpp#340]
I am recreating the game 'Your first game Dodge the Creeps!” from the documentation and there is only one thing missing I could not find a way around, it is the yield implementation.

```
func show_game_over():
	show_message("Game Over")
	yield($MessageTimer, "timeout")
	$MessageLabel.text = "Dodge the\nCreeps"
	$MessageLabel.show()
	yield(get_tree().create_timer(1), 'timeout')
	$StartButton.show()
```

How can I re implement it with GDNative?

**Comment by BastiaanOlij** [comment]
Sorry for the late reply. Yield is a kind of strange function as its not really a function. Basically it ends processing of the method right there and then and registers a single call linked to a trigger. 

I'm not sure what the equivalent code to register the trigger would be but behind the scenes your method would actually be split into 3 methods each on ending with setting the trigger to run the next function in sequence.

**Comment by ricardoalcantara** [comment]
Thanks for the reply, I ended up doing what you suggested. And there is no way to exactly translate this code to GDNative, I am closing the issue.
