### ISSUE TITLE
is Vector2 missing bounce function?

### ISSUE THREAD

**Issue by fhausman** [GodotNativeTools/godot-cpp#347]
According to https://docs.godotengine.org/en/3.1/classes/class_vector2.html I'd expect to have `bounce` function available in `Vector2` class. Currently there is no such function in `Vector2`

**Comment by 2shady4u** [comment]
Hello @fhausman , a lot of the functionalities contained in the Godot Engine are not available in GDNative as GDNative tends to lag behind a bit on functionalities...

I saw that the bounce functionality is actually fully supported (in the Engine and in the headers), so I added this functionality in #362

**Comment by 2shady4u** [comment]
This has been merged and can thus be closed @BastiaanOlij
