### ISSUE TITLE
i can't compile for android via gdnative

### ISSUE THREAD

**Issue by IuryBorges1993** [GodotNativeTools/godot-cpp#351]
Godot 3.1+

Ubuntu 18.04

i can't compile for android via gdnative

OK
![Captura de tela de 2019-11-22 18-17-19](https://user-images.githubusercontent.com/39449626/69476455-ef68fc80-0db8-11ea-9746-04febc396d1c.png)
Ok
![Captura de tela de 2019-11-22 18-18-03](https://user-images.githubusercontent.com/39449626/69476457-f263ed00-0db8-11ea-965e-5dcc6a18f02e.png)
Fall
![Captura de tela de 2019-11-22 18-41-38](https://user-images.githubusercontent.com/39449626/69476458-f5f77400-0db8-11ea-9b8e-cb3b83c5ec95.png)

everything was going well, when I got to the final stage the error started -> aarch64-linux-android/bin/ld: cannot find -lgodot-cpp.android.debug.armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Project github: https://github.com/IuryBorges1993/port-demo-kinematic_character-para-android

I followed this tutorial, still the error at the end -> https://github.com/GodotNativeTools/godot-cpp#compiling-the-cpp-bindings-library

**Comment by bruvzg** [comment]
You are using 64-bit compiler (`aarch64-`) with 32-bit (`.armv7`) library. Rebuild `godot-cpp` with `android_arch=arm64v8`.

**Comment by IuryBorges1993** [comment]
thanks
