### ISSUE TITLE
Object.hpp: No such file or directory

### ISSUE THREAD

**Issue by hungrymonkey** [GodotNativeTools/godot-cpp#37]
I been trying to build a simple class
```
 gcc -fPIC -o src/init.os -c src/init.cpp -g -O3 -std=c++14 -Icpp_bindings/include -Igodot_headers -Icpp_bindings/include/core
In file included from src/init.cpp:1:0:
cpp_bindings/include/core/Godot.hpp:15:10: fatal error: Object.hpp: No such file or directory
 #include <Object.hpp>
```

I wondering how does godot-cpp build without an object header anywhere.

on another note, -Icpp_bindings/include is mentioned twice in the readme. I would had made a pull request to fix it if I manage to get this thing compiling

**Comment by RameshRavone** [comment]
May be you already figured this, If not you have to generated C++ bindings, before compiling
```
scons godotbinpath="${GODOT_ROOT}/bin/" headers="../godot_headers/" generate_bindings=yes
```
Note: Don't forget to add `use_llvm=yes` for clang

**Comment by hungrymonkey** [comment]
@RameshRavone  thank you.
