### ISSUE TITLE
Build fails : 'alloca' was not declared in this scope. Missing include statement ?

### ISSUE THREAD

**Issue by omomthings** [GodotNativeTools/godot-cpp#376]
Platform Windows 10,
Compiler MinGW Build-20200227-1 version 9.2.0,
Godot-CPP branch 3.2

I had a problem compiling using the following command 
`scons p=windows generate_bindings=yes bits=64  use_mingw=yes -j8`

I had the following issue:

> =====
src\gen\FuncRef.cpp: In member function 'godot::Variant godot::FuncRef::call_func(const godot::Array&)':
src\gen\FuncRef.cpp:35:46: error: 'alloca' was not declared in this scope; did you mean 'malloc'?
   35 |  godot_variant **__args = (godot_variant **) alloca(sizeof(godot_variant *) * (__var_args.size() + 0));
      |                                              ^~~~~~
      |                                              malloc

>=====
scons: *** [src\gen\FuncRef.o] Error 1
=====
src\gen\GDScript.cpp: In member function 'godot::Variant godot::GDScript::new_(const godot::Array&)':
src\gen\GDScript.cpp:35:46: error: 'alloca' was not declared in this scope; did you mean 'malloc'?
   35 |  godot_variant **__args = (godot_variant **) alloca(sizeof(godot_variant *) * (__var_args.size() + 0));
      |                                              ^~~~~~
      |                                              malloc

>=====
scons: *** [src\gen\GDScript.o] Error 1

It seems like the alloca.h file was missing, I had to add it manually in the `binding_generator.py` file in the `def generate_class_implementation(icalls, used_classes, c)` function definition, like this :
## Original file:
`....
    source.append("#include \"__icalls.hpp\"")
    source.append("")
    source.append("")
....
`
## Which became : 
`....
    source.append("#include \"__icalls.hpp\"")
    source.append("#include \"alloca.h\"")
    source.append("")
....
`

That fixed my build.
Is a PR required for this ?

**Comment by SeleDreams** [comment]
Thanks for the solution, I was having the same issue, I think a PR would be good

**Comment by Zylann** [comment]
On Windows, I've seen `alloca` defined in `malloc.h`. The include may need to be different depending on the platform/compiler.

**Comment by Zylann** [comment]
I attempted a PR, let me know if it works for you

**Comment by bruvzg** [comment]
There's no `alloca.h` header in any standard MinGW distribution, when cross-building it will pick-up system one, but won't work on Windows. Should be `malloc.h` on Windows.

**Comment by bruvzg** [comment]
And IIRC `alloca` might be in the `stdlib.h` on some (or all) BSD distros. At least according to OpenBSD [man](https://man.openbsd.org/alloca.3), Godot have it included [latform_config.h#L34-L35](https://github.com/godotengine/godot/blob/master/platform/linuxbsd/platform_config.h#L34-L35).
