### ISSUE TITLE
Error when calling move_and_slide(...) inside _physics_process

### ISSUE THREAD

**Issue by GeorgeGRz** [GodotNativeTools/godot-cpp#377]
Hello, I followed the standard tutorial and extended it a bit, adding one more class called Movement. This class is assigned on kinetmaticbody2d and extends this class as well. The problem comes when calling move_and_slide inside _physics_process. I will also give you all the code which includes my Godot project . Sadly because its too large I tried to compress it using the highest compression but still I cannot post it here, so I will send you we transfer link from which you can download the source code. 
Thank you.
Download link is: https://we.tl/t-d51tLxw7HS
PS: My platform is Linux Ubuntu.

**Comment by GeorgeGRz** [comment]
[backtrace.txt](https://github.com/GodotNativeTools/godot-cpp/files/4343982/backtrace.txt)
Here is the backtrace I extracted when running the game.

**Comment by GeorgeGRz** [comment]
[src.zip](https://github.com/GodotNativeTools/godot-cpp/files/4343996/src.zip)

**Comment by sheepandshepherd** [comment]
Here's the backtrace for when godot-cpp calls `move_and_slide`:
```cpp
[3] godot::KinematicBody2D::move_and_slide(godot::Vector2, godot::Vector2, float, long, float) (??:0)
```
Those are the arguments that function had in Godot 3.0. Unfortunately, they were changed in Godot 3.1:
```gdscript
Vector2 linear_velocity, Vector2 floor_normal=Vector2( 0, 0 ), bool stop_on_slope=false, int max_slides=4, float floor_max_angle=0.785398, bool infinite_inertia=true
```
Breaking changes like this aren't supposed to happen, but this one got through before it was noticed, so 3.0 bindings are incompatible with Godot 3.2.1.

To fix this, you should update both `godot-cpp` and `godot_headers`. Run `git pull` and `git submodule update` in your `godot-cpp/` directory. Then rebuild the bindings. Make sure to pass `generate_bindings=yes` to scons.

**Comment by GeorgeGRz** [comment]
Everything seems to be up to date, problem still persists.

**Comment by GeorgeGRz** [comment]
Yes, I solved the issue with the help of @sheepandshepherd . The main reason was that I generated the bindings using `godot3 .....` command instead of using the default appImage I downloaded. Problem solved.
