### ISSUE TITLE
Generated TriangleMesh class doesn't contain any method

### ISSUE THREAD

**Issue by amina-refik** [GodotNativeTools/godot-cpp#379]
Hi,
I am trying to access the list of all vertices in a triangular mesh. i tried looking in the godot source code, and i found them stored in the triangleMesh class. but in the generated include files of godot-cpp project, TriangleMesh class doesn't contain any method.

**Comment by Zylann** [comment]
This is not a Godot-Cpp bug. `TriangleMesh` really does not have any *exposed* methods: https://docs.godotengine.org/en/stable/classes/class_trianglemesh.html
