### ISSUE TITLE
Recreating starter kit in newest master branch

### ISSUE THREAD

**Issue by Kerrex** [GodotNativeTools/godot-cpp#38]
Hello,
I'm having troubles at recreating starter kit in newest master branch. I've successfully managed to replace both include and lib folders to latest version of bindings and init.cpp file compiles but I get following error in Godot:
`undefined symbol: _Z18gdnative_terminateP32godot_gdnative_terminate_options`

Here's my init.cpp: 
https://pastebin.com/YPPiDRzF (I'm aware that some stuff could be done better, e.g "owner" field but I was looking for simplest solution.
I would appreciate any help :)

**Comment by RameshRavone** [comment]
change: 
```
gdnative_terminate(godot_gdnative_terminate_options *o)
```
to
```
godot_gdnative_terminate(godot_gdnative_terminate_options *o)
```

**Comment by Kerrex** [comment]
Thanks for pointing me back to readme :D Looks like I missed superclass change in test class :)
