### ISSUE TITLE
Problem compiling on g++ 9.3.0

### ISSUE THREAD

**Issue by DaedricSpartan99** [GodotNativeTools/godot-cpp#386]
Try to build with the following command:
`scons platform=linux generate_bindings=yes -j2 use_custom_api_file=yes custom_api_file=../api.json bits=64`
it generates the following error:
```
g++ -o src/ResourceFormatLoaderCrypto.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/core src/ResourceFormatLoaderCrypto.cpp
In file included from include/ResourceFormatLoaderCrypto.hpp:11,
                 from src/ResourceFormatLoaderCrypto.cpp:1:
include/ResourceFormatLoader.hpp:31:41: error: expected nested-name-specifier before ')' token
   31 |  bool handles_type(const String typename);
      |                                         ^
include/ResourceFormatLoader.hpp:31:41: error: two or more data types in declaration of 'parameter'
g++ -o src/VScrollBar.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/core src/VScrollBar.cpp
scons: *** [src/ResourceFormatLoaderCrypto.o] Error 1
scons: building terminated because of errors.
```
Taking a look to the involved file I see that a variable was called `typename`, is that a mistake or was there a particular purpose no more supported in the newest version of g++?
It appears that the files ResourceFormatLoader.hpp and .cpp are auto-generated in compile time,
where should I modify in order to change the variable name?
Another remark: I followed the documentation [(https://docs.godotengine.org/en/stable/tutorials/plugins/gdnative/gdnative-cpp-example.html)]

**Comment by Zylann** [comment]
Had a look at the generated code, it's not named `typename`, but `_typename`. Thanks to this https://github.com/GodotNativeTools/godot-cpp/blob/c2f765e49c7dd0c86729e6ba17f87c039203bce0/binding_generator.py#L792

Do you have latest version?

**Comment by DaedricSpartan99** [comment]
Ok thank you, in fact that wasn't the latest version, I thought that 3.0 branch was the latest one. The 3.0 should be removed from the GDNative docs.
