### ISSUE TITLE
Condition "!script_data" is true

### ISSUE THREAD

**Issue by DaedricSpartan99** [GodotNativeTools/godot-cpp#387]
```
ERROR: _update_placeholder: Condition "!script_data" is true.
   At: modules/gdnative/nativescript/nativescript.cpp:92.
```
This error is showing up when loading a script in a node inspector.
What does this mean?
Eventually is a GDNative plugin supposed to be "single class", in the sense that 
only one class can be registered by a plugin? (I'm asking because it could be the cause of the error)

**Comment by Zylann** [comment]
> is a GDNative plugin supposed to be "single class", in the sense that
only one class can be registered by a plugin?

No, a GDNative library can contain multiple classes.

**Comment by DaedricSpartan99** [comment]
Ok, this is good as clarification.
And about that error, how can I troubleshoot it? Is it a way to say that my plugin is crashing internally?
Or is it a configuration issue?
In the .gdns file are there some conditions to match in the variable names with respect to the c++ code class names?

**Comment by DaedricSpartan99** [comment]
Update: I saw that putting the exact c++ class name into the class_name variable in the .gdns file,
the error disappeared. Then is it correct to say that every class present in plugin must have its own .gdns file with the corresponding class name?

**Comment by Zylann** [comment]
@DaedricSpartan99 I can imagine if class names don't match, it could cause trouble yeah

**Comment by Lecrapouille** [comment]
Just for information: I got this error message. I exported two c++ classes and I spent time before noticing that I had an error of copy and paste with the class name inside the macro `GODOT_CLASS̀` in the class. I was pretty sure the issue was in the gdns or gdnlib files.
