### ISSUE TITLE
Dealing with references

### ISSUE THREAD

**Issue by DaedricSpartan99** [GodotNativeTools/godot-cpp#388]
I'm wondering how godot::Reference class should be used inside the C++ code.
Is it more correct storing it into a pointer or a simple variable?
I'll clarify with an example:
```
class MyRef : public Reference {
    GODOT_CLASS(MyRef, Reference)
public:
    ... // all needed code 
};

class MyRefUse : public Node {
   GODOT_CLASS(MyRefUse, Node)
   MyRef * m_ref; // should it be a pointer or an simple field?
public:
    ... // _init, constructor, destructor
    void set_myref(MyRef * ref) {
        m_ref = ref;
    }

    MyRef * get_myref() {
        return m_ref;
    }

    static void _register_methods() {
        register_property<MyRefUse, MyRef*>("myref", &MyRefUse::set_myref, &MyRefUse::get_myref, nullptr);
        ... // register other methods
    }
};
```
And both classes are registered.
Update: in case `get_myref()` returns a pointer to a copy of m_ref (then `new MyRef(*m_ref)`),
how the engine would manage the pointer delection? Will it delete the pointer normally as the reference count goes to zero, or will it result in memory leak? Thank you for a response

**Comment by Zylann** [comment]
References are best used with a `Ref<T>` wrapper, as it will take care of handing refcounting for you. Otherwise, `reference()` and `unref` must be called manually when your code grabs or releases ownership.
However, there are known issues with `Ref` in the tracker, where leaks happen.

**Comment by DaedricSpartan99** [comment]
Thank you
As you explained, I followed your solution, but when I'm trying to create a `Ref` that instance destroys immediately the internal object (the `Reference` one), as the ref_count seems to be initialized to zero.
Which are the conditions to match in order to properly create a Reference?
At the moment there are the following methods:

- `void _init()` member
- A constructor which takes no arguments
- A destructor
- `GODOT_CLASS(myclassname, Reference)`
- `static void _register_methods()` member
What have I forgotten?

Furthermore I tried with the approach mentioned in this thread [](https://www.reddit.com/r/godot/comments/bogn0s/how_to_create_and_return_custom_class_from/) but I seems 
not working.

**Comment by Zylann** [comment]
I don't know, I only assume references should work the same way as they do in the engine, but GDNative seems to have some quirks and bugs that aren't figured out yet

**Comment by DaedricSpartan99** [comment]
After some debugging I found the following things:

- `init_ref()` returns `true` (I found the value by override and super-class call)
- calling `_new()` erases directly the object, this is unexpected
- contrarely to the Godot version, `is_referenced()` is not present, then I cannot check for its behaviour
- initializing the object by pointer (new operator) the object is maintained but initializing the Ref with that pointer the program crashes

**Comment by DaedricSpartan99** [comment]
FInally `Ref<T>` works fine for instances initialized in a gdscript and then passed inside a gdnative c++ code.
