### ISSUE TITLE
move_and_slide doesn't work

### ISSUE THREAD

**Issue by GittyGrubHub85** [GodotNativeTools/godot-cpp#396]
void Player::_physics_process(float delta){

	time_passed += delta;
	Vector2 motion = Vector2();
	motion.x = 5;
	Vector2 result = move_and_slide(motion); //-> this function doesn't work

  }

I'm having a problem my player doesn't move even just by using move_and_slide function. It should work normally as what other suggest but when they found out they can't answer the problem. I look up to the branch of the nativescript I'm in and it's on 1.1 so I hope I'm on the right branch of godot-cpp.

**Comment by sheepandshepherd** [comment]
Use the `master` branch of godot-cpp. `1.1` is old, so probably won't work with up-to-date Godot. `move_and_slide` had an unplanned breaking change since Godot 3.0.
