### ISSUE TITLE
fatal error C1083: Cannot open include file: 'gdnative/vector3.h': No such file or directory

### ISSUE THREAD

**Issue by GittyGrubHub85** [GodotNativeTools/godot-cpp#398]
I got an error with compiler (MSVC 19.14+) while compiling with scons

> scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cl /Fosrc\core\AABB.obj /c src\core\AABB.cpp /TP /nologo /Z7 /Od /EHsc /D_DEBUG /MDd /I. /Igodot_headers /Iinclude /Iinclude\gen /Iinclude\core
AABB.cpp
e:\godot\godot 3.2\projects (own)\gdnative c++ based on documents\my gdnative c++ creation\godot-cpp\include\core\Vector3.hpp(4) : fatal error C1083: Cannot open include file: 'gdnative/vector3.h': No such file or directory
scons: *** [src\core\AABB.obj] Error 2
scons: building terminated because of errors.

**Comment by BastiaanOlij** [comment]
When cloning this repository did you clone recursively? Sounds like godot_headers isn't included.

Else just run:
```
git submodule init
git submodule update
```
Within your godot-cpp folder

**Comment by GittyGrubHub85** [comment]
Never mind, my scons is probably STILL using an older version like 12.0 since I had multiple older versions of MSVC in my x86 Program Files folder so I removed the older versions in my C drive and scons is now using newer versions of it, completely.
