### ISSUE TITLE
Linking fails

### ISSUE THREAD

**Issue by blicksyne** [GodotNativeTools/godot-cpp#44]
I was told this is a better place to post this than AnswerHub, so the text below is mostly the same as it over there. In the meantime (during past couple of days) another person confirmed he's getting the same errors, we're both using Windows and MSVC. I tried again last night, with all the repos at latest commits, and the issue is still there, for me at least.

Here's a video demonstrating the issue:
https://www.youtube.com/watch?v=43JPCOEBEG0

Here are the linking errors from the output:
https://pastebin.com/zAkXSSgn

Below I posted some of the relevant project settings from a CMake project where I get these errors. The Visual Studio project is set up exactly the same and I get the same linking errors. I believe the includes and libraries are correctly set up as everything worked properly previously. The issue appeared a few days ago (could be something wrong with my setup, but I don't think I changed anything).

These are the includes I use:

${CMAKE_CURRENT_SOURCE_DIR}/../godot_headers
${CMAKE_CURRENT_SOURCE_DIR}/../godot-cpp/include/core
${CMAKE_CURRENT_SOURCE_DIR}/../godot-cpp/include

I link to these two libraries:

${CMAKE_CURRENT_SOURCE_DIR}/../godot/bin/godot.windows.tools.64.lib
${CMAKE_CURRENT_SOURCE_DIR}/../godot-cpp/bin/godot_cpp_bindings.lib

Here's the folder structure:
https://ibb.co/d3kZfb

The "godot_cpp_bindings.lib" and "godot.windows.tools.64.lib" are compiled from the most recent commit from a few hours ago from the godot and godot-cpp repositories. The godot_headers repo was also up-to-date.

I'm on Windows 10, I tried using MSVC2015 and MSVC2017.

**Comment by RameshRavone** [comment]
Questing, are you using the current head of the master branch of Godot repo, or the alpha release,

If yes, try using the latest head of three repos, `godot_headers`, `godot-cpp` and `godot`

**Comment by blicksyne** [comment]
Yes, I'm on the latest commit from the master branch. Here's where I am in all the repositories:
https://photos.app.goo.gl/LTx9XoGirMf7XmQf2

I usually compile godot with these commands (compiling twice because of mono):
scons -j6 -c p=windows
scons -j6 p=windows target=debug tools=yes mono_glue=no module_mono_enabled=yes
bin\godot.windows.tools.64.exe --generate-mono-glue modules/mono/glue
scons -j6 vsproj=yes p=windows target=debug tools=yes module_mono_enabled=yes

But I also tried compiling without mono, so it's not mono-related:
scons -j6 -c p=windows
scons -j6 vsproj=yes p=windows target=debug tools=yes module_mono_enabled=no

After that I run these commands in the godot-cpp folder:
In order to get rid of the generated header and .cpp files, in case those might be the culprits:
git clean -n
git clean -f
git clean -n -X
git clean -f -X

Then this of course:
scons -c
scons -j6 godotbinpath="../godot/bin/" headers="../godot_headers/" p=windows generate_bindings=yes

Then I try building either my CMake or VS project, which are set up like I explained in the original post.

Any ideas?

**Comment by RameshRavone** [comment]
Yes, you need to pass `godotlibpath` for windows.

**Comment by blicksyne** [comment]
call scons -j6 godotbinpath="../godot/bin/" godotlibpath="../godot/bin/" headers="../godot_headers/" p=windows generate_bindings=yes
Like this? Same result. I already had godotbinpath and godotlibpath set up in the SConstruct file, so these are probably redundant but I'm passing them just in case.

Anything else I should check? Can you reproduce this?

**Comment by blicksyne** [comment]
Here's my CMakeLists file:
[CMakeLists.txt](https://github.com/GodotNativeTools/godot-cpp/files/1382463/CMakeLists.txt)

**Comment by RameshRavone** [comment]
I don't have a windows with me, I use almighty `Linux` :penguin:,

But by looking at your error, The only possible problem should have been `godot_headers` or the `*.lib` being older than [4ae5759](https://github.com/GodotNativeTools/godot_headers/commit/23872837e77e39ba6ab21393f26e531d1ae0a7b6)

**Comment by RameshRavone** [comment]
build godot with `gdnative_wrapper=yes`

**Comment by blicksyne** [comment]
Sorry, compilation took a long time, but the results are in now. Nothing changed :) I checked that file and it got generated during this compilation. This also got generated: gdnative_wrapper_code.windows.tools.64.lib, but it didn't help.

**Comment by karroffel** [comment]
I need to update the bindings to use the API struct that was introduced recently. Then there won't be a static library from Godot to link against anymore. The wrapper library could/should work, but I'd rather have the bindings not use them and access the struct directly. I don't know when I'm gonna implement that, but I plan to.

As always, PRs are welcome :P (In this case making all the `godot_xxx` calls use the API struct pointer and updating the build system so there's no dependency on any static library anymore).
