### ISSUE TITLE
CONNECT_DEFERRED already defined on Windows

### ISSUE THREAD

**Issue by Trigve** [GodotNativeTools/godot-cpp#46]
CONNECT_DEFERRED enum in Object::ConnectFlags is already defined on Windows.

It could be fixed either to giver it some prefix as CF_CONNECT_DEFERRED or use some different coding style for enums as ConnectDeferred.

**Comment by karroffel** [comment]
Would using enum classes solve this?

**Comment by Trigve** [comment]
I don't think so.  CONNECT_DEFERRED is #define, so it would be replaced by pre-processor everywhere.
Anyway, I'm testing the build (with some other problems :) ) and will let you know if enum class could work.

**Comment by BastiaanOlij** [comment]
I remember this issue from a long time ago. I believe it was fixed.  CONNECT_DEFERRED  is no longer part of the godot-cpp source code (I believe it was used in Godot itself?).
I'm closing this issue. Please re-open if I turn out to be wrong :)
