### ISSUE TITLE
Compile Error: Godot.hpp:15:10: fatal error: Object.hpp: No such file or directory

### ISSUE THREAD

**Issue by JosephCatrambone** [GodotNativeTools/godot-cpp#59]
I'm building on Windows with the current github master (bde1ce384fa0e9244ee5fb67c81fceb4c96e1f1d) and am running into a 'no such file' issue.  From the looks of the repo, Object.hpp isn't defined and I can't find it elsewhere in Godot's source or in the godot_headers repo.

Full text of the error (with run command):

```
D:\Source\TerminusExperiment\CPU_v1>g++ -g -fPIC -std=c++14 src\init.cpp -Icpp_bindings\include -Igodot_headers -ID:\Source\godot\ -ID:\Source\godot\modules\gdnative\include -o lib\init.obj
In file included from src\init.cpp:22:0:
cpp_bindings\include/core/Godot.hpp:15:10: fatal error: Object.hpp: No such file or directory
 #include <Object.hpp>
          ^~~~~~~~~~~~
compilation terminated.
```

At the time of writing, there is indeed no Object.hpp in the path: https://github.com/GodotNativeTools/godot-cpp/tree/master/include/core

**Comment by karroffel** [comment]
There are only a few files that are manually written, the rest gets generated automatically.

So the Object.hpp doesn't exist before generating it.

`scons p=YOUROS godotbinpath=/path/to/godot(.exe) headers=/path/to/gdnative/include/or/godot_headers generate_bindings=yes`

This will generate the all the bindings.

**Comment by JosephCatrambone** [comment]
Much obliged.  I can't generate any bindings still, but that's a problem for me to solve.

**Comment by MathiasBaumgartinger** [comment]
For anyone interested, this has worked for me:
```scons platform=windows generate_bindings=yes bits=64```
