### ISSUE TITLE
utf8 error spam

### ISSUE THREAD

**Issue by amirea** [GodotNativeTools/godot-cpp#60]
Godot 3.0 beta 1, Windows 10
I'm getting [Godot #11440](https://github.com/godotengine/godot/issues/11440) kind of error again. Lots of `invalid skip`, `invalid utf8`, `overlong rejected`, and `no space left`.

**Comment by karroffel** [comment]
The referenced issue concludes that this is a calling side error.

Unless it's some string in the bindings that causes this there is nothing I can do about it. :.
