### ISSUE TITLE
Arrays are freed too early

### ISSUE THREAD

**Issue by Geequlim** [GodotNativeTools/godot-cpp#64]
Here I registered a property `buttons`
```c++
class NativeMessageDialog : public  GDNativeDialog {
    GODOT_SUBCLASS(NativeMessageDialog, GDNativeDialog);
protected:
    String message;
    Array buttons;

public:
    static void _register_methods() {
        register_property<NativeMessageDialog, String>("message", &NativeMessageDialog::message, "");
        register_property<NativeMessageDialog, Array>("buttons", &NativeMessageDialog::buttons, Array());
    }
};
```

Then I use this class in GDScript as this.

```gdscript
var msg_dialog = NativeMessageDialog.new()
func _ready():
	msg_dialog.message = "This message is send from GDScript by GDNative"
	msg_dialog.buttons = ["Apply", "Cancel"]
     	msg_dialog.show()

func _on_Show_Message_pressed():
	# BUG: array are freed
        # msg_dialog.buttons = ["Apply", "Cancel"]
	msg_dialog.show()
```

The function `Array.size` is called by `show` to create buttons for the dialog.
The firs call of `show` works fine.
The second call of `show` crash my program as it call `Array.size` but the `buttons` is already freed.

**Comment by karroffel** [comment]
They shouldn't be freed before the script instance gets destroyed.

Do you know where exactly they are freed? It just seems like they aren't valid anymore in the _on_Show_Message_pressed(), but I can't see here *where* they get freed.
