### ISSUE TITLE
Cannot use Ref<T> where T is a GodotScript<T>

### ISSUE THREAD

**Issue by Zylann** [GodotNativeTools/godot-cpp#77]
I have a custom resource type, but the code won't compile because T has no `reference()` function, only the `owner` of `GodotScript<T>` does.  I'm not sure how to solve this...

The workaround I might use is to instead make my property expect a `Ref<Resource>` and cast the userdata on it to my custom class, which is obviously unsafe, but I don't see a better option at the moment.

GDNative exposes `nativescript_api->godot_nativescript_get_userdata(obj)` to get the custom classs instance as a `void*`, however there is not enough info to verify that pointer, unless each library tracks every single pointer it shares with Godot through this API, and fetches it back... basically, rewriting `ObjectDB`.
Such `ObjectDB` would also need to be thread-safe as well, unless we don't use Godot threads and rewrite ours.

## type tags
As an example, in the Squirrel scripting language, integer typetags are carried along `void*` pointers, which allows to identify the native types of such userdatas, which makes it safer to retrieve them. Those typetags may come from a memory address, typically a static pointer per class, which by nature will be unique as long as the corresponding library is in memory (that tag could even be generated by GDNative actually). Type check would even easily be thread-safe. But GDNative doesn't have this, so rewriting a thread-safe ObjectDB in each library is the only option for now...

**Comment by sheepandshepherd** [comment]
The `Ref` template should probably have a specialization for GodotScript types that passes those function calls on to `owner`. There will still need to be safe casts in the method/property wrappers, but otherwise this way of handling custom-type Refs is simple and preserves the type at compile-time (without type tags).

**Comment by karroffel** [comment]
Alternatively we could add a macro

`GODOT_REF_CLASS` that implements `reference()` and `unreference()` and simply forwards them to the `owner`. 

@sheepandshepherd template specializations for things that inherit some template base class is not very ... easy nor pretty. :D

I faced a situation where exactly that would have been needed too, but it's just such a pain to do, I decided to make use of the compile time ducktyping in templates.

This is the commit I'm talking about. 7dde412e26315447edf2f46661143082b5becf32

The sad truth there is that it's easier to add a method to ALL THE CLASSES than do such a template specialization.

If you know a way to do it nicely then I'm happy to make that code nicer to work with and do the same for Ref, I'm honestly curious of how to do it without resorting to C++17 features :D

**Comment by karroffel** [comment]
This needs some more tweaking, but this is now possible on the `nativescript-1.1` branch!

**Comment by Zylann** [comment]
@karroffel also if you look at the PR I did on the old version, I had it nearly working with SFINAE :p

**Comment by BastiaanOlij** [comment]
Is this still valid now that we're on nativescript 1.1?

**Comment by Zylann** [comment]
If Nativescript 1.1 doesn't have `GodotScript<T>`, I think the issue would be irrelevant, or different if it still exists.

**Comment by BastiaanOlij** [comment]
Agreed, if there still is an issue, just re-open one when you get back into working on GDNative. Thanks:)
