### ISSUE TITLE
How to reference custom GodotScripts?

### ISSUE THREAD

**Issue by Zylann** [GodotNativeTools/godot-cpp#91]
Let's say I expose this `foo` function:

```cpp
class MyRef GodotScript<Reference> { 
    // ...
}

void NativeTest::foo(MyRef *arg) {
    // stuff
}
```

How can `MyRef` be safely referenced? The function is not explicitely adding to the refcount in any way, which means the following situation would either produce a dangling pointer, or a leak:

```gdscript
func _ready():
    native_test.foo(MyRef.new())
```

Unless this is done to keep the reference alive:

```cpp
void NativeTest::foo(MyRef *arg) {
    m_myref_holder = Ref<Reference>(arg->owner);
}
```

The only "transparennt" way I can think of is to modify `Ref` in such a way it can reference `GodotScript`, so this could be written:

```cpp
void NativeTest::foo(Ref<MyRef> arg {
    //...
}
```

**Comment by BastiaanOlij** [comment]
I'm repeating myself :) Is this still an issue @Zylann ? Is this comparable to what I'm doing in procmesh? Here I have a bunch of GDNative subclasses that I parse back and forwards with references but using Nativescript 1.1

**Comment by Zylann** [comment]
I havent used GDNative in months, but if GodotScript<T> went away then this issue would be irrelevant.

**Comment by BastiaanOlij** [comment]
@Zylann you should give it another try :)

Just trying to clean up a bit, @karroffel whats your feel about the status of the issues Marc ran into, this was part of why you changed a lot around memory management?

**Comment by karroffel** [comment]
Yes, the biggest point of the NativeScript 1.1 extension is that the "model" for references, scripts and engine-types are all unified. He ran into many issues, but I think most of them were related to this

**Comment by BastiaanOlij** [comment]
Then I suggest we close these for now, @Zylann hopefully you're able to try out the new version in due time, please open a new updated issue if you still run into troubles, thanks :)
