### ISSUE TITLE
Nativescript 1.1: object destruction leads to infinite recursion

### ISSUE THREAD

**Issue by Zylann** [GodotNativeTools/godot-cpp#98]
In the nativescript-1.1 branch:

An object deleted by Godot with a NativeScript on it leads to infinite recursion.

This is caused by the fact now library classes use full inheritance, but there is no clear control over the ownership of objects. When Godot destroys its object, it also destroys the NativeScript that was on it, which calls the destruction function on the C++ bindings side, which in turn attempts to destroy the Godot object.

![image](https://user-images.githubusercontent.com/1311555/36360435-211915a6-1524-11e8-8cfc-552aec3124e9.png)

A similar case of errors may happen with object creation, because both `new` and `delete` were overrided in the bindings side, making it impossible to use the vanilla versions of them when needed (you may not always need to create or destroy the underlying Godot object).

**Comment by Zylann** [comment]
Here are some thoughts I noted:
Custom classes can now inherit Godot class bindings, which means we need to be careful about creation, destruction and ownership.
Godot will be responsible for calling the actual deletion of library classes inheriting Godot ones.


The main idea is to introduce additional new and delete functions, and leave the originals vanilla.

new Sprite() from the library will create a Sprite binding, and nothing else. It won't call Godot in any way. So it's not recommended to use by a library coder, vanilla is reserved for internal use.

Sprite::create() will create a Sprite binding, create a Sprite, and attach the binding to it.

Passing a Sprite to the library will try to fetch a Sprite binding from those attached to the object. If not found, will allocate a new Sprite binding and attach it to the existing Sprite.
Note: the binding class will always match the Godot class, however if it's a custom class, typetag checking may happen.

delete Sprite from the library will delete the binding, and nothing else. Not recommended, reserved for internal use.

Sprite::free() on library side will destroy the underlying Godot object, which will remove the attached bindings, and call delete func on them. The same will happen when Godot destroys the object from GDScript.

References will simply build on top of the above logic.


Because custom classes are in the same inheritance tree, they should be treated the same. The only difference is, their object attachment is unique because their class is only defined in one library. They may also use typetags because they are unknown to the engine.


Now, something strange:
How to dynamically attach the CustomClass script on a Sprite? Inheritance is not the same as script attachement, so there is a dodge to do here.

The only way is to do this:

auto *s = Sprite::create();

Ref<Script> cc = ResourceLoader::get_singleton()->load("res//addons/zylann.test/custom_class.gdns");

s->set_script(cc);

auto *c = cast<CustomClass>(s);

**Comment by karroffel** [comment]
@Zylann  Seems fair, I'll see if I can get around to implement that.

`create` and `free` might be taken, but the general idea still applies, could work :)
